#DSSR_PATH="/home/raktim/rnaprodb/rnaprodb/dssr_output/"
#CIF_PATH="/home/raktim/rnaprodb/rnaprodb_frontend/public/cifs/"
#FIG_PATH="/home/raktim/rnaprodb/rnaprodb_frontend/public/rnaview"

# DSSR_PATH="/home/raktim/rnaview/json/"
# CIF_PATH="/home/raktim/rnaview/vn/"
# FIG_PATH="/processed_images/"
# MEDIA_PATH = "/home/raktim/rnaview/backend/media/"

DSSR_PATH="/home/aricohen/Desktop/rnaview/json/"
CIF_PATH="/home/aricohen/Desktop/rnaview/vn/"
FIG_PATH="/processed_images/"
MEDIA_PATH = "/home/aricohen/Desktop/rnaview/backend/media/"
X3DNA_PATH = "/home/aricohen/Desktop/DeepPBS/dependencies/bin/x3dna-dssr"
CWD = "/home/aricohen/Desktop/rnaview/"